.TH seat-inspect 1 "March 2015"
.SH NAME
seat-inspect \- enumerate status of systemd facilities

.SH SYNOPSIS
.B seat-inspect
[\fB\-v, \-\-verbose]
[\fB\-nc, \-\-nocolour]

.SH DESCRIPTION
.B seat\-inspect
gives a status report of systemd facilities such as
Multi\-Seat, Inhibitor Locks, Services, Targets, and other types of
Unit.
.PP
The intent of running the code is to have an overview of the system
status, both to see what the new facilities are about, and to figure out
if there is something out of place.
.PP
The intent of reading the code is to have an idea of how to use these
facilities: the code has been written to be straightforward and is
annotated with relevant bits from the logind and systemd D-Bus API
documentation.

.SH OPTIONS
.nf
\-v,\ \-\-verbose
       Log all available detail. Overrides the default behaviour of
       only logging information about real or potential errors.

\-nc,\ \-\-nocolour
       Disables default insertion of ANSI escape codes for colour coded
       output. Useful if you want to redirect the output for sharing.
.fi

.SH NOTES
To learn more about how \f[B]seat-inspect\f[] works, and the facilities it
reports on, consult the following sources of documentation:
.PP
.nf
http://www.freedesktop.org/wiki/Software/systemd/logind/
http://www.freedesktop.org/wiki/Software/systemd/dbus/
http://www.freedesktop.org/wiki/Software/systemd/multiseat/
http://www.freedesktop.org/wiki/Software/systemd/
.fi

